"""add relationship task for tag and tag for task

Revision ID: 564a150be61f
Revises: 6f51ccd402ca
Create Date: 2024-06-27 15:35:49.985401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564a150be61f'
down_revision: Union[str, None] = '6f51ccd402ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
