"""Initial migration

Revision ID: c830d6b9bbe6
Revises: 
Create Date: 2024-06-25 16:04:20.842015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c830d6b9bbe6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_first_name', sa.String(length=15), nullable=False),
    sa.Column('user_second_name', sa.String(length=20), nullable=False),
    sa.Column('user_middle_name', sa.String(length=25), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_pass', sa.String(length=255), nullable=False),
    sa.Column('user_position', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
