"""delete user_id with task

Revision ID: 06036b70b81b
Revises: b18a12fe5787
Create Date: 2024-07-10 14:09:35.509065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06036b70b81b"
down_revision: Union[str, None] = "b18a12fe5787"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tasks_user_id_fkey", "tasks", type_="foreignkey")
    op.drop_column("tasks", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "tasks_user_id_fkey", "tasks", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
