"""add user_id foreignkey for roles

Revision ID: 735819fd4579
Revises: 83bd946abaab
Create Date: 2024-07-04 15:10:36.118420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "735819fd4579"
down_revision: Union[str, None] = "83bd946abaab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "roles", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.drop_column("roles", "user_id")
    # ### end Alembic commands ###
