"""Init

Revision ID: 83bd946abaab
Revises: 
Create Date: 2024-07-04 13:07:02.666347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83bd946abaab"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "role_name",
            sa.String(length=100),
            server_default="Пользователь",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "tag_name",
            sa.String(length=100),
            server_default="Пользователь",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "task_date_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "task_name", sa.String(), server_default="Задача", nullable=False
        ),
        sa.Column("task_body", sa.Text(), nullable=False),
        sa.Column(
            "task_status",
            sa.String(length=50),
            server_default="Не выполнена",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_first_name",
            sa.String(length=15),
            server_default="Максим",
            nullable=False,
        ),
        sa.Column(
            "user_second_name",
            sa.String(length=20),
            server_default="Максимов",
            nullable=False,
        ),
        sa.Column(
            "user_middle_name",
            sa.String(length=25),
            server_default="Максимович",
            nullable=False,
        ),
        sa.Column("user_email", sa.String(length=255), nullable=False),
        sa.Column("user_pass", sa.String(length=255), nullable=False),
        sa.Column("user_position", sa.String(length=255), nullable=True),
        sa.Column(
            "user_date_creation",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_email"),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("image_path", sa.String(length=200), nullable=False),
        sa.Column(
            "image_date_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("images")
    op.drop_table("users")
    op.drop_table("tasks")
    op.drop_table("tags")
    op.drop_table("roles")
    # ### end Alembic commands ###
